# fly.toml file generated for katias-blog on 2023-02-07T20:49:11+01:00

app = "katias-blog"
primary_region = "fra"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/staticfiles"  # <-- Updated!
  url_prefix = "/static"